name: Build and Publish n8n FFmpeg

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/anbu-raj/n8n-ffmpeg:latest
            ghcr.io/anbu-raj/n8n-ffmpeg:2.10.2
